# Generated by Django 5.0.1 on 2024-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_receipt_report_myuser_temporary_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_game_keeper',
            field=models.BooleanField(default=False),
        ),
    ]
