# Generated by Django 5.0.2 on 2024-03-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_report_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='username',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
